/**
 * GENERATED by scripts/gen-measure-catalog.mjs — do not edit by hand.
 * The full 60-measure TWH catalog (OSHA safety + HEDIS wellness + CMS eCQM) the
 * /measures page reads, sourced from the Java seed (MeasureService.CMS_ECQM_CATALOG +
 * the OSHA/HEDIS seed + V017). Lifecycle mutations (create/approve/activate/deprecate,
 * spec/CQL edits) are a later slice and need a persisted measures store; this is the
 * read catalog. The 10 Active measures are exactly the engine's runnable set.
 */
export type MeasureStatus = "Draft" | "Approved" | "Active" | "Deprecated";

export interface CatalogMeasure {
  id: string;
  name: string;
  policyRef: string;
  version: string;
  status: MeasureStatus;
  owner: string;
  tags: string[];
}

export const MEASURE_CATALOG: readonly CatalogMeasure[] = [
  { id: "audiogram", name: "Annual Audiogram Completed", policyRef: "OSHA 29 CFR 1910.95", version: "v1.0", status: "Active", owner: "system", tags: ["surveillance","hearing","osha"] },
  { id: "hazwoper", name: "HAZWOPER Surveillance", policyRef: "OSHA 29 CFR 1910.120", version: "v1.0", status: "Active", owner: "system", tags: ["surveillance","hazmat","osha"] },
  { id: "tb_surveillance", name: "TB Surveillance", policyRef: "CDC TB Screening Guidance", version: "v1.0", status: "Active", owner: "system", tags: ["surveillance","infection-control","cdc"] },
  { id: "flu_vaccine", name: "Flu Vaccine", policyRef: "CDC Seasonal Influenza Guidance", version: "v1.0", status: "Active", owner: "system", tags: ["vaccine","seasonal","immunization"] },
  { id: "hypertension", name: "Hypertension BP Screening", policyRef: "HEDIS BPC / JPMC Wellness Rewards", version: "v1.0", status: "Active", owner: "system", tags: ["wellness","hypertension","cardiovascular"] },
  { id: "diabetes_hba1c", name: "Diabetes HbA1c Monitoring", policyRef: "HEDIS HBD / JPMC Wellness Rewards", version: "v1.0", status: "Active", owner: "system", tags: ["wellness","diabetes","hba1c"] },
  { id: "obesity_bmi", name: "BMI Screening & Counseling", policyRef: "HEDIS WCC / Cigna Healthcare Wellness", version: "v1.0", status: "Active", owner: "system", tags: ["wellness","bmi","obesity"] },
  { id: "cholesterol_ldl", name: "Cholesterol LDL Screening", policyRef: "HEDIS CBP / JPMC Wellness Rewards", version: "v1.0", status: "Active", owner: "system", tags: ["wellness","cholesterol","cardiovascular"] },
  { id: "respirator_fit_test", name: "Respirator Fit Test", policyRef: "OSHA 29 CFR 1910.134", version: "v0.9", status: "Draft", owner: "J. Chen", tags: ["surveillance","respiratory","osha"] },
  { id: "hepatitis_b_vaccination_series", name: "Hepatitis B Vaccination Series", policyRef: "OSHA 29 CFR 1910.1030", version: "v2.0", status: "Approved", owner: "K. Williams", tags: ["vaccine","bbp","osha"] },
  { id: "lead_medical_surveillance", name: "Lead Medical Surveillance", policyRef: "OSHA 29 CFR 1910.1025", version: "v1.1", status: "Deprecated", owner: "M. Patel", tags: ["surveillance","lead","osha"] },
  { id: "cms2v15", name: "Preventive Care and Screening: Screening for Depression and Follow-Up Plan", policyRef: "CMS2v15", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","mental-health","preventive"] },
  { id: "cms128v14", name: "Antidepressant Medication Management", policyRef: "CMS128v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","mental-health","depression"] },
  { id: "cms159v14", name: "Depression Remission at Twelve Months", policyRef: "CMS159v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","mental-health","depression"] },
  { id: "cms177v14", name: "Child and Adolescent Major Depressive Disorder (MDD): Suicide Risk Assessment", policyRef: "CMS177v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","mental-health","pediatric"] },
  { id: "cms149v14", name: "Dementia: Cognitive Assessment", policyRef: "CMS149v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","mental-health","dementia"] },
  { id: "cms136v15", name: "Follow-Up Care for Children Prescribed ADHD Medication", policyRef: "CMS136v15", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","mental-health","pediatric"] },
  { id: "cms137v14", name: "Initiation and Engagement of Substance Use Disorder Treatment", policyRef: "CMS137v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","substance-use"] },
  { id: "cms22v14", name: "Preventive Care and Screening Screening for High Blood Pressure and Follow Up Documented", policyRef: "CMS22v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","preventive"] },
  { id: "cms135v14", name: "Heart Failure (HF): Angiotensin-Converting Enzyme (ACE) Inhibitor or Angiotensin Receptor Blocker (ARB) or Angiotensin Receptor-Neprilysin Inhibitor (ARNI) Therapy for Left Ventricular Systolic Dysfunction (LVSD)", policyRef: "CMS135v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","heart-failure"] },
  { id: "cms144v14", name: "Heart Failure (HF): Beta-Blocker Therapy for Left Ventricular Systolic Dysfunction (LVSD)", policyRef: "CMS144v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","heart-failure"] },
  { id: "cms145v14", name: "Coronary Artery Disease (CAD): Beta-Blocker Therapy-Prior Myocardial Infarction (MI) or Left Ventricular Systolic Dysfunction (LVEF ≤40%)", policyRef: "CMS145v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular"] },
  { id: "cms165v14", name: "Controlling High Blood Pressure", policyRef: "CMS165v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","hypertension"] },
  { id: "cms347v9", name: "Statin Therapy for the Prevention and Treatment of Cardiovascular Disease", policyRef: "CMS347v9", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","statin"] },
  { id: "cms90v15", name: "Functional Status Assessments for Heart Failure", policyRef: "CMS90v15", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","heart-failure","functional-status"] },
  { id: "cms1173v1", name: "Diagnostic Delay of Venous Thromboembolism in Primary Care", policyRef: "CMS1173v1", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cardiovascular","vascular"] },
  { id: "cms122", name: "Diabetes: Glycemic Status Assessment Greater Than 9%", policyRef: "CMS122v14", version: "v1.0", status: "Active", owner: "WorkWell Studio", tags: ["ecqm","cms","diabetes"] },
  { id: "cms131v14", name: "Diabetes: Eye Exam", policyRef: "CMS131v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","diabetes","ophthalmology"] },
  { id: "cms142v14", name: "Diabetic Retinopathy: Communication with the Physician Managing Ongoing Diabetes Care", policyRef: "CMS142v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","diabetes","ophthalmology"] },
  { id: "cms951v4", name: "Kidney Health Evaluation", policyRef: "CMS951v4", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","nephrology","diabetes"] },
  { id: "cms1154v1", name: "Screening for Abnormal Glucose Metabolism in Patients at Risk of Developing Diabetes", policyRef: "CMS1154v1", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","diabetes","preventive"] },
  { id: "cms124v14", name: "Cervical Cancer Screening", policyRef: "CMS124v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cancer-screening","preventive"] },
  { id: "cms125", name: "Breast Cancer Screening", policyRef: "CMS125v14", version: "v1.0", status: "Active", owner: "WorkWell Studio", tags: ["ecqm","cms","cancer-screening","preventive"] },
  { id: "cms130v14", name: "Colorectal Cancer Screening", policyRef: "CMS130v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","cancer-screening","preventive"] },
  { id: "cms69v14", name: "Preventive Care and Screening Body Mass Index (BMI) Screening and Follow Up Plan", policyRef: "CMS69v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","preventive","bmi"] },
  { id: "cms138v14", name: "Preventive Care and Screening: Tobacco Use: Screening and Cessation Intervention", policyRef: "CMS138v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","preventive","tobacco"] },
  { id: "cms139v14", name: "Falls: Screening for Future Fall Risk", policyRef: "CMS139v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","preventive","falls"] },
  { id: "cms155v14", name: "Weight Assessment and Counseling for Nutrition and Physical Activity for Children/Adolescents", policyRef: "CMS155v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","preventive","pediatric"] },
  { id: "cms153v14", name: "Chlamydia Screening in Women", policyRef: "CMS153v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","preventive","womens-health"] },
  { id: "cms146v14", name: "Appropriate Testing for Pharyngitis", policyRef: "CMS146v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","respiratory","antimicrobial-stewardship"] },
  { id: "cms154v14", name: "Appropriate Treatment for Upper Respiratory Infection (URI)", policyRef: "CMS154v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","respiratory","antimicrobial-stewardship"] },
  { id: "cms117v14", name: "Childhood Immunization Status", policyRef: "CMS117v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","immunization","pediatric"] },
  { id: "cms74v15", name: "Primary Caries Prevention Intervention as Offered by Dentists", policyRef: "CMS74v15", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","dental","pediatric"] },
  { id: "cms75v14", name: "Children Who Have Dental Decay or Cavities", policyRef: "CMS75v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","dental","pediatric"] },
  { id: "cms314v3", name: "HIV Viral Suppression", policyRef: "CMS314v3", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","infectious-disease","hiv"] },
  { id: "cms349v8", name: "HIV Screening", policyRef: "CMS349v8", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","infectious-disease","hiv","preventive"] },
  { id: "cms1157v2", name: "HIV Annual Retention in Care", policyRef: "CMS1157v2", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","infectious-disease","hiv"] },
  { id: "cms1188v3", name: "Sexually Transmitted Infection (STI) Testing for People with HIV", policyRef: "CMS1188v3", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","infectious-disease","hiv","sti"] },
  { id: "cms129v15", name: "Prostate Cancer Avoidance of Overuse of Bone Scan for Staging Low Risk Prostate Cancer Patients", policyRef: "CMS129v15", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","oncology"] },
  { id: "cms157v14", name: "Oncology: Medical and Radiation - Pain Intensity Quantified", policyRef: "CMS157v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","oncology","pain"] },
  { id: "cms646v6", name: "Intravesical Bacillus-Calmette-Guerin for Non-Muscle Invasive Bladder Cancer", policyRef: "CMS646v6", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","oncology"] },
  { id: "cms645v9", name: "Bone Density Evaluation for Patients with Prostate Cancer and Receiving Androgen Deprivation Therapy", policyRef: "CMS645v9", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","oncology","musculoskeletal"] },
  { id: "cms133v14", name: "Cataracts: 20/40 or Better Visual Acuity within 90 Days Following Cataract Surgery", policyRef: "CMS133v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","ophthalmology"] },
  { id: "cms143v14", name: "Primary Open-Angle Glaucoma (POAG): Optic Nerve Evaluation", policyRef: "CMS143v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","ophthalmology"] },
  { id: "cms56v14", name: "Functional Status Assessment for Total Hip Replacement", policyRef: "CMS56v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","functional-status","orthopedic"] },
  { id: "cms68v15", name: "Documentation of Current Medications in the Medical Record", policyRef: "CMS68v15", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","medication-safety","patient-safety"] },
  { id: "cms156v14", name: "Use of High-Risk Medications in Older Adults", policyRef: "CMS156v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","medication-safety","geriatric"] },
  { id: "cms50v14", name: "Closing the Referral Loop: Receipt of Specialist Report", policyRef: "CMS50v14", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","care-coordination"] },
  { id: "cms771v7", name: "Urinary Symptom Score Change 6-12 Months After Diagnosis of Benign Prostatic Hyperplasia", policyRef: "CMS771v7", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","urology"] },
  { id: "cms1056v3", name: "Excessive Radiation Dose or Inadequate Image Quality for Diagnostic Computed Tomography (CT) in Adults (Clinician Level)", policyRef: "CMS1056v3", version: "v1.0", status: "Draft", owner: "WorkWell Studio", tags: ["ecqm","cms","radiology","patient-safety"] },
];
