/**
 * Hand-maintained: the full 60-measure TWH catalog (summary + authoring spec). Originally
 * generated from the Java seed (MeasureService.CMS_ECQM_CATALOG + the OSHA/HEDIS seed + V017);
 * that generator (scripts/gen-measure-catalog.mjs) was retired with the JVM in #109 PR4, so this
 * file is now the canonical source — edit it directly. The 10 Active measures are
 * exactly the engine's runnable set; `cqlText`/`compileStatus` are derived at request time
 * (reconstructed ELM for runnable measures). Lifecycle mutations need a persisted store (later).
 */
export type MeasureStatus = "Draft" | "Approved" | "Active" | "Deprecated";

export interface TestFixture {
  fixtureName: string;
  employeeExternalId: string;
  expectedOutcome: string;
  notes: string;
}

export interface MeasureSpec {
  description: string;
  eligibilityCriteria: { roleFilter: string; siteFilter: string; programEnrollmentText: string };
  exclusions: Array<{ label: string; criteriaText: string }>;
  complianceWindow: string;
  requiredDataElements: string[];
  testFixtures: TestFixture[];
}

export interface CatalogMeasure {
  id: string;
  name: string;
  policyRef: string;
  version: string;
  status: MeasureStatus;
  owner: string;
  tags: string[];
  /** Compile gate state: COMPILED (has working CQL) | NOT_COMPILED (catalog/Draft). */
  compileStatus: string;
  spec: MeasureSpec;
}

export const MEASURE_CATALOG: readonly CatalogMeasure[] = [
  {"id":"audiogram","name":"Annual Audiogram Completed","policyRef":"OSHA 29 CFR 1910.95","version":"v1.0","status":"Active","owner":"system","tags":["surveillance","hearing","osha"],"compileStatus":"COMPILED","spec":{"description":"Annual audiogram monitoring for noise-exposed employees.","eligibilityCriteria":{"roleFilter":"Maintenance Tech, Welder","siteFilter":"Plant A, Plant B","programEnrollmentText":"Hearing Conservation Program"},"exclusions":[{"label":"Waiver","criteriaText":"Valid audiogram waiver on file"}],"complianceWindow":"Annual","requiredDataElements":["Last audiogram date","Role","Site","Program enrollment"],"testFixtures":[{"fixtureName":"Compliant — audiogram within annual window","employeeExternalId":"emp-001","expectedOutcome":"COMPLIANT","notes":"120 days since last exam; threshold 335 days"},{"fixtureName":"Due soon — audiogram approaching due date","employeeExternalId":"emp-002","expectedOutcome":"DUE_SOON","notes":"350 days since last exam; DUE_SOON window 336–365"},{"fixtureName":"Overdue — annual audiogram past due","employeeExternalId":"emp-003","expectedOutcome":"OVERDUE","notes":"420 days since last exam; threshold 365 days"},{"fixtureName":"Missing data — no audiogram on record","employeeExternalId":"emp-004","expectedOutcome":"MISSING_DATA","notes":"No exam date present in employee record"},{"fixtureName":"Excluded — active audiogram waiver on file","employeeExternalId":"emp-005","expectedOutcome":"EXCLUDED","notes":"Valid waiver exempts from annual requirement"}]}},
  {"id":"hazwoper","name":"HAZWOPER Surveillance","policyRef":"OSHA 29 CFR 1910.120","version":"v1.0","status":"Active","owner":"system","tags":["surveillance","hazmat","osha"],"compileStatus":"COMPILED","spec":{"description":"Annual HAZWOPER medical surveillance for hazardous-waste operations employees.","eligibilityCriteria":{"roleFilter":"Industrial Hygienist, Maintenance Tech","siteFilter":"Plant A, Plant B","programEnrollmentText":"HAZWOPER Program"},"exclusions":[{"label":"Exemption","criteriaText":"Temporary medical exemption documented"}],"complianceWindow":"Annual","requiredDataElements":["Last surveillance exam date","Role","Site","Exemption status"],"testFixtures":[{"fixtureName":"Compliant — HAZWOPER surveillance current","employeeExternalId":"emp-003","expectedOutcome":"COMPLIANT","notes":"120 days since HAZWOPER exam; threshold 335 days"},{"fixtureName":"Due soon — HAZWOPER surveillance approaching","employeeExternalId":"emp-008","expectedOutcome":"DUE_SOON","notes":"355 days since exam; DUE_SOON window 335–365"},{"fixtureName":"Overdue — HAZWOPER surveillance past due","employeeExternalId":"emp-013","expectedOutcome":"OVERDUE","notes":"380 days since exam; threshold 365 days"},{"fixtureName":"Missing data — no HAZWOPER exam on record","employeeExternalId":"emp-018","expectedOutcome":"MISSING_DATA","notes":"No surveillance exam date in employee record"},{"fixtureName":"Excluded — HAZWOPER medical exemption on file","employeeExternalId":"emp-023","expectedOutcome":"EXCLUDED","notes":"Medical exemption exempts from annual requirement"}]}},
  {"id":"tb_surveillance","name":"TB Surveillance","policyRef":"CDC TB Screening Guidance","version":"v1.0","status":"Active","owner":"system","tags":["surveillance","infection-control","cdc"],"compileStatus":"COMPILED","spec":{"description":"Annual TB surveillance for clinic-based nursing and clinic staff.","eligibilityCriteria":{"roleFilter":"Nurse, Clinic Staff","siteFilter":"Clinic","programEnrollmentText":"Occupational TB Screening Program"},"exclusions":[{"label":"Medical Exemption","criteriaText":"Valid exemption documented"}],"complianceWindow":"Annual","requiredDataElements":["Last TB screening date","Role","Site","Exemption status"],"testFixtures":[{"fixtureName":"Compliant — TB screen within annual window","employeeExternalId":"emp-041","expectedOutcome":"COMPLIANT","notes":"120 days since last TB screen; threshold 330 days"},{"fixtureName":"Due soon — TB screen approaching due date","employeeExternalId":"emp-045","expectedOutcome":"DUE_SOON","notes":"365 days since last screen; DUE_SOON window 330–365"},{"fixtureName":"Overdue — TB screen past due","employeeExternalId":"emp-046","expectedOutcome":"OVERDUE","notes":"380 days since last screen; threshold 365 days"},{"fixtureName":"Missing data — no TB screen on record","employeeExternalId":"emp-049","expectedOutcome":"MISSING_DATA","notes":"No TB screen date in employee record"},{"fixtureName":"Excluded — TB medical exemption on file","employeeExternalId":"emp-050","expectedOutcome":"EXCLUDED","notes":"Medical exemption exempts from TB screening requirement"}]}},
  {"id":"flu_vaccine","name":"Flu Vaccine","policyRef":"CDC Seasonal Influenza Guidance","version":"v1.0","status":"Active","owner":"system","tags":["vaccine","seasonal","immunization"],"compileStatus":"COMPILED","spec":{"description":"Seasonal influenza vaccination compliance for active employees.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"Plant A, Plant B, Clinic","programEnrollmentText":"Seasonal Flu Program"},"exclusions":[{"label":"Clinical Contraindication","criteriaText":"Documented contraindication for current season"}],"complianceWindow":"Seasonal","requiredDataElements":["Last flu vaccine date","Current season","Contraindication status"],"testFixtures":[{"fixtureName":"Compliant — flu vaccine documented this season","employeeExternalId":"emp-001","expectedOutcome":"COMPLIANT","notes":"Vaccine administered within the current flu season window"},{"fixtureName":"Missing data — no flu vaccine record found","employeeExternalId":"emp-021","expectedOutcome":"MISSING_DATA","notes":"No vaccine record present; employee is clinical-facing and not exempt"},{"fixtureName":"Excluded — documented vaccine contraindication","employeeExternalId":"emp-032","expectedOutcome":"EXCLUDED","notes":"Valid medical contraindication exempts from flu vaccine requirement"}]}},
  {"id":"hypertension","name":"Hypertension BP Screening","policyRef":"HEDIS BPC / JPMC Wellness Rewards","version":"v1.0","status":"Active","owner":"system","tags":["wellness","hypertension","cardiovascular"],"compileStatus":"COMPILED","spec":{"description":"Annual blood pressure screening for employees enrolled in the wellness program.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"All Sites","programEnrollmentText":"Wellness Program"},"exclusions":[{"label":"Medical Exemption","criteriaText":"Documented medical exemption on file"}],"complianceWindow":"Annual","requiredDataElements":["Last BP screening date","Program enrollment","Exemption status"],"testFixtures":[]}},
  {"id":"diabetes_hba1c","name":"Diabetes HbA1c Monitoring","policyRef":"HEDIS HBD / JPMC Wellness Rewards","version":"v1.0","status":"Active","owner":"system","tags":["wellness","diabetes","hba1c"],"compileStatus":"COMPILED","spec":{"description":"Biannual HbA1c lab monitoring for employees enrolled in the diabetes management program.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"All Sites","programEnrollmentText":"Diabetes Management Program"},"exclusions":[{"label":"Medical Exemption","criteriaText":"Documented medical exemption on file"}],"complianceWindow":"Biannual (180 days)","requiredDataElements":["Last HbA1c lab date","Program enrollment","Exemption status"],"testFixtures":[]}},
  {"id":"obesity_bmi","name":"BMI Screening & Counseling","policyRef":"HEDIS WCC / Cigna Healthcare Wellness","version":"v1.0","status":"Active","owner":"system","tags":["wellness","bmi","obesity"],"compileStatus":"COMPILED","spec":{"description":"Annual BMI screening and counseling for employees enrolled in the wellness program.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"All Sites","programEnrollmentText":"Wellness Program"},"exclusions":[{"label":"Medical Exemption","criteriaText":"Documented medical exemption on file"}],"complianceWindow":"Annual","requiredDataElements":["Last BMI screening date","Program enrollment","Exemption status"],"testFixtures":[]}},
  {"id":"cholesterol_ldl","name":"Cholesterol LDL Screening","policyRef":"HEDIS CBP / JPMC Wellness Rewards","version":"v1.0","status":"Active","owner":"system","tags":["wellness","cholesterol","cardiovascular"],"compileStatus":"COMPILED","spec":{"description":"Annual LDL cholesterol lab screening for employees enrolled in the cardiovascular risk program.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"All Sites","programEnrollmentText":"Cholesterol Risk Program"},"exclusions":[{"label":"Medical Exemption","criteriaText":"Documented medical exemption on file"}],"complianceWindow":"Annual","requiredDataElements":["Last LDL lab date","Program enrollment","Exemption status"],"testFixtures":[]}},
  {"id":"respirator_fit_test","name":"Respirator Fit Test","policyRef":"OSHA 29 CFR 1910.134","version":"v0.9","status":"Draft","owner":"J. Chen","tags":["surveillance","respiratory","osha"],"compileStatus":"NOT_COMPILED","spec":{"description":"Annual medical evaluation and fit test for employees required to use respiratory protection under OSHA 1910.134.","eligibilityCriteria":{"roleFilter":"Maintenance Tech, Paint Crew, Chemical Handler","siteFilter":"Plant A, Plant B","programEnrollmentText":"Enrolled in Respiratory Protection Program"},"exclusions":[{"label":"Medical Clearance Waiver","criteriaText":"Physician-issued respirator clearance waiver on file"}],"complianceWindow":"365 days from last fit test","requiredDataElements":["Respirator Type","Last Fit Test Date","Medical Clearance Status"],"testFixtures":[]}},
  {"id":"hepatitis_b_vaccination_series","name":"Hepatitis B Vaccination Series","policyRef":"OSHA 29 CFR 1910.1030","version":"v2.0","status":"Approved","owner":"K. Williams","tags":["vaccine","bbp","osha"],"compileStatus":"COMPILED","spec":{"description":"Hepatitis B vaccination series completion for employees with occupational exposure to blood or other potentially infectious materials.","eligibilityCriteria":{"roleFilter":"Nurse, Lab Technician, Phlebotomist, Emergency Responder","siteFilter":"Clinic, Medical Center","programEnrollmentText":"Bloodborne pathogen exposure risk role"},"exclusions":[{"label":"Documented Immunity","criteriaText":"Positive anti-HBs titer on file"}],"complianceWindow":"Series of 3 doses over 6 months","requiredDataElements":["HBV Dose 1 Date","HBV Dose 2 Date","HBV Dose 3 Date","Anti-HBs Titer Result"],"testFixtures":[]}},
  {"id":"lead_medical_surveillance","name":"Lead Medical Surveillance","policyRef":"OSHA 29 CFR 1910.1025","version":"v1.1","status":"Deprecated","owner":"M. Patel","tags":["surveillance","lead","osha"],"compileStatus":"COMPILED","spec":{"description":"DEPRECATED — Replaced by updated Lead Exposure Monitoring Protocol. Blood lead level monitoring for employees exposed to lead above the action level.","eligibilityCriteria":{"roleFilter":"Battery Plant Worker, Smelter, Lead Paint Handler","siteFilter":"Plant A","programEnrollmentText":"Lead exposure above action level (30 µg/m³)"},"exclusions":[],"complianceWindow":"Every 6 months for blood lead monitoring","requiredDataElements":["Blood Lead Level (µg/dL)","Exam Date"],"testFixtures":[]}},
  {"id":"cms2v15","name":"Preventive Care and Screening: Screening for Depression and Follow-Up Plan","policyRef":"CMS2v15","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","mental-health","preventive"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS2v15 (MIPS Quality ID 134) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms128v14","name":"Antidepressant Medication Management","policyRef":"CMS128v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","mental-health","depression"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS128v14 (MIPS Quality ID 009) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms159v14","name":"Depression Remission at Twelve Months","policyRef":"CMS159v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","mental-health","depression"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS159v14 (MIPS Quality ID 370) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms177v14","name":"Child and Adolescent Major Depressive Disorder (MDD): Suicide Risk Assessment","policyRef":"CMS177v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","mental-health","pediatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS177v14 (MIPS Quality ID 382) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms149v14","name":"Dementia: Cognitive Assessment","policyRef":"CMS149v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","mental-health","dementia"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS149v14 (MIPS Quality ID 281) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms136v15","name":"Follow-Up Care for Children Prescribed ADHD Medication","policyRef":"CMS136v15","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","mental-health","pediatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS136v15 (MIPS Quality ID 366) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms137v14","name":"Initiation and Engagement of Substance Use Disorder Treatment","policyRef":"CMS137v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","substance-use"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS137v14 (MIPS Quality ID 305) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms22v14","name":"Preventive Care and Screening Screening for High Blood Pressure and Follow Up Documented","policyRef":"CMS22v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","preventive"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS22v14 (MIPS Quality ID 317) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms135v14","name":"Heart Failure (HF): Angiotensin-Converting Enzyme (ACE) Inhibitor or Angiotensin Receptor Blocker (ARB) or Angiotensin Receptor-Neprilysin Inhibitor (ARNI) Therapy for Left Ventricular Systolic Dysfunction (LVSD)","policyRef":"CMS135v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","heart-failure"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS135v14 (MIPS Quality ID 005) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms144v14","name":"Heart Failure (HF): Beta-Blocker Therapy for Left Ventricular Systolic Dysfunction (LVSD)","policyRef":"CMS144v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","heart-failure"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS144v14 (MIPS Quality ID 008) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms145v14","name":"Coronary Artery Disease (CAD): Beta-Blocker Therapy-Prior Myocardial Infarction (MI) or Left Ventricular Systolic Dysfunction (LVEF ≤40%)","policyRef":"CMS145v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS145v14 (MIPS Quality ID 007) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms165v14","name":"Controlling High Blood Pressure","policyRef":"CMS165v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","hypertension"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS165v14 (MIPS Quality ID 236) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms347v9","name":"Statin Therapy for the Prevention and Treatment of Cardiovascular Disease","policyRef":"CMS347v9","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","statin"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS347v9 (MIPS Quality ID 438) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms90v15","name":"Functional Status Assessments for Heart Failure","policyRef":"CMS90v15","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","heart-failure","functional-status"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS90v15 (MIPS Quality ID 377) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms1173v1","name":"Diagnostic Delay of Venous Thromboembolism in Primary Care","policyRef":"CMS1173v1","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cardiovascular","vascular"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS1173v1 (MIPS Quality ID 514) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms122","name":"Diabetes: Glycemic Status Assessment Greater Than 9%","policyRef":"CMS122v14","version":"v1.0","status":"Active","owner":"WorkWell Studio","tags":["ecqm","cms","diabetes"],"compileStatus":"COMPILED","spec":{"description":"Diabetes: HbA1c Poor Control (CMS122v14 / MIPS 1): patients 18–75 with diabetes whose most recent HbA1c result is > 9% (poor control). OVERDUE indicates intervention is needed.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"All Sites","programEnrollmentText":"Diabetes Diagnosis"},"exclusions":[{"label":"Clinical Exclusion","criteriaText":"Hospice care, advanced illness, or other clinical exclusion"}],"complianceWindow":"Annual — based on HbA1c value, not recency","requiredDataElements":["Most recent HbA1c lab value","Diabetes diagnosis","Exclusion status"],"testFixtures":[]}},
  {"id":"cms131v14","name":"Diabetes: Eye Exam","policyRef":"CMS131v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","diabetes","ophthalmology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS131v14 (MIPS Quality ID 117) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms142v14","name":"Diabetic Retinopathy: Communication with the Physician Managing Ongoing Diabetes Care","policyRef":"CMS142v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","diabetes","ophthalmology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS142v14 (MIPS Quality ID 019) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms951v4","name":"Kidney Health Evaluation","policyRef":"CMS951v4","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","nephrology","diabetes"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS951v4 (MIPS Quality ID 488) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms1154v1","name":"Screening for Abnormal Glucose Metabolism in Patients at Risk of Developing Diabetes","policyRef":"CMS1154v1","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","diabetes","preventive"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS1154v1 (MIPS Quality ID 515) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms124v14","name":"Cervical Cancer Screening","policyRef":"CMS124v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cancer-screening","preventive"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS124v14 (MIPS Quality ID 309) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms125","name":"Breast Cancer Screening","policyRef":"CMS125v14","version":"v1.0","status":"Active","owner":"WorkWell Studio","tags":["ecqm","cms","cancer-screening","preventive"],"compileStatus":"COMPILED","spec":{"description":"Breast Cancer Screening (CMS125v14 / MIPS 112): women 50–74 who had a mammogram in the measurement period or 26 months prior.","eligibilityCriteria":{"roleFilter":"All","siteFilter":"All Sites","programEnrollmentText":"Breast Cancer Screening Eligible"},"exclusions":[{"label":"Clinical Exclusion","criteriaText":"Bilateral mastectomy or history of breast cancer — documented exclusion on file"}],"complianceWindow":"27 months (820 days)","requiredDataElements":["Last mammogram date","Eligible population flag","Exclusion status"],"testFixtures":[]}},
  {"id":"cms130v14","name":"Colorectal Cancer Screening","policyRef":"CMS130v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","cancer-screening","preventive"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS130v14 (MIPS Quality ID 113) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms69v14","name":"Preventive Care and Screening Body Mass Index (BMI) Screening and Follow Up Plan","policyRef":"CMS69v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","preventive","bmi"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS69v14 (MIPS Quality ID 128) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms138v14","name":"Preventive Care and Screening: Tobacco Use: Screening and Cessation Intervention","policyRef":"CMS138v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","preventive","tobacco"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS138v14 (MIPS Quality ID 226) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms139v14","name":"Falls: Screening for Future Fall Risk","policyRef":"CMS139v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","preventive","falls"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS139v14 (MIPS Quality ID 318) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms155v14","name":"Weight Assessment and Counseling for Nutrition and Physical Activity for Children/Adolescents","policyRef":"CMS155v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","preventive","pediatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS155v14 (MIPS Quality ID 239) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms153v14","name":"Chlamydia Screening in Women","policyRef":"CMS153v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","preventive","womens-health"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS153v14 (MIPS Quality ID 310) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms146v14","name":"Appropriate Testing for Pharyngitis","policyRef":"CMS146v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","respiratory","antimicrobial-stewardship"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS146v14 (MIPS Quality ID 066) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms154v14","name":"Appropriate Treatment for Upper Respiratory Infection (URI)","policyRef":"CMS154v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","respiratory","antimicrobial-stewardship"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS154v14 (MIPS Quality ID 065) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms117v14","name":"Childhood Immunization Status","policyRef":"CMS117v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","immunization","pediatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS117v14 (MIPS Quality ID 240) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms74v15","name":"Primary Caries Prevention Intervention as Offered by Dentists","policyRef":"CMS74v15","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","dental","pediatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS74v15 (MIPS Quality ID 379) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms75v14","name":"Children Who Have Dental Decay or Cavities","policyRef":"CMS75v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","dental","pediatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS75v14 (MIPS Quality ID 378) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms314v3","name":"HIV Viral Suppression","policyRef":"CMS314v3","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","infectious-disease","hiv"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS314v3 (MIPS Quality ID 338) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms349v8","name":"HIV Screening","policyRef":"CMS349v8","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","infectious-disease","hiv","preventive"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS349v8 (MIPS Quality ID 475) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms1157v2","name":"HIV Annual Retention in Care","policyRef":"CMS1157v2","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","infectious-disease","hiv"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS1157v2 (MIPS Quality ID 340) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms1188v3","name":"Sexually Transmitted Infection (STI) Testing for People with HIV","policyRef":"CMS1188v3","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","infectious-disease","hiv","sti"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS1188v3 (MIPS Quality ID 205) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms129v15","name":"Prostate Cancer Avoidance of Overuse of Bone Scan for Staging Low Risk Prostate Cancer Patients","policyRef":"CMS129v15","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","oncology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS129v15 (MIPS Quality ID 102) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms157v14","name":"Oncology: Medical and Radiation - Pain Intensity Quantified","policyRef":"CMS157v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","oncology","pain"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS157v14 (MIPS Quality ID 143) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms646v6","name":"Intravesical Bacillus-Calmette-Guerin for Non-Muscle Invasive Bladder Cancer","policyRef":"CMS646v6","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","oncology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS646v6 (MIPS Quality ID 481) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms645v9","name":"Bone Density Evaluation for Patients with Prostate Cancer and Receiving Androgen Deprivation Therapy","policyRef":"CMS645v9","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","oncology","musculoskeletal"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS645v9 (MIPS Quality ID 462) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms133v14","name":"Cataracts: 20/40 or Better Visual Acuity within 90 Days Following Cataract Surgery","policyRef":"CMS133v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","ophthalmology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS133v14 (MIPS Quality ID 191) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms143v14","name":"Primary Open-Angle Glaucoma (POAG): Optic Nerve Evaluation","policyRef":"CMS143v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","ophthalmology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS143v14 (MIPS Quality ID 012) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms56v14","name":"Functional Status Assessment for Total Hip Replacement","policyRef":"CMS56v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","functional-status","orthopedic"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS56v14 (MIPS Quality ID 376) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms68v15","name":"Documentation of Current Medications in the Medical Record","policyRef":"CMS68v15","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","medication-safety","patient-safety"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS68v15 (MIPS Quality ID 130) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms156v14","name":"Use of High-Risk Medications in Older Adults","policyRef":"CMS156v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","medication-safety","geriatric"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS156v14 (MIPS Quality ID 238) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms50v14","name":"Closing the Referral Loop: Receipt of Specialist Report","policyRef":"CMS50v14","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","care-coordination"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS50v14 (MIPS Quality ID 374) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms771v7","name":"Urinary Symptom Score Change 6-12 Months After Diagnosis of Benign Prostatic Hyperplasia","policyRef":"CMS771v7","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","urology"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS771v7 (MIPS Quality ID 476) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
  {"id":"cms1056v3","name":"Excessive Radiation Dose or Inadequate Image Quality for Diagnostic Computed Tomography (CT) in Adults (Clinician Level)","policyRef":"CMS1056v3","version":"v1.0","status":"Draft","owner":"WorkWell Studio","tags":["ecqm","cms","radiology","patient-safety"],"compileStatus":"NOT_COMPILED","spec":{"description":"CMS1056v3 (MIPS Quality ID 494) — CMS eCQM 2026 performance period catalog entry. CQL authoring pending.","eligibilityCriteria":{"roleFilter":"","siteFilter":"","programEnrollmentText":""},"exclusions":[],"complianceWindow":"Annual","requiredDataElements":[],"testFixtures":[]}},
];
