ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS requested_scope_json JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS failure_summary TEXT;

ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS partial_failure_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS dry_run BOOLEAN NOT NULL DEFAULT FALSE;
