// AUTO-GENERATED by scripts/gen-measure-bindings.mjs from the YAML measure defs — do not edit.
/**
 * Measure bindings (#107 run pipeline; ADR-031 export semantics) — the codes/value sets +
 * compliance window the synthetic FHIR builder stamps per employee, plus MeasureReport
 * interpretation flags. `event.type` drives the resource kind: procedure | immunization |
 * observation. Source of truth: the YAML measure definitions; regenerate on re-seed.
 */
export type EventType = "procedure" | "immunization" | "observation";

export interface CodeBinding {
  code: string;
  valueSet: string;
}

export interface SeriesBinding {
  requiredDoses: number;
}

/** E11.2c — one alternative dose series for a multi-brand series-completion measure (Hep B
 * Heplisav-vs-traditional). `codes` are bare CVX strings under `event.valueSet`; the synthetic dose
 * model picks one alternative per employee and stamps its codes/spacing. */
export interface SeriesAlternativeBinding {
  label: string;
  requiredDoses: number;
  codes: string[];
  minIntervalDays?: number[];
}

export interface MeasureBinding {
  rateKey: string;
  improvementNotation: "increase" | "decrease";
  complianceClass: "PERMANENT" | "RECURRING";
  complianceWindowDays: number;
  enrollment: CodeBinding;
  waiver: CodeBinding;
  event: CodeBinding & { type: EventType };
  refusal?: CodeBinding;
  series?: SeriesBinding;
  gracePeriodDays?: number;
  alternatives?: SeriesAlternativeBinding[];
  missingDataMeansOutOfPopulation?: boolean;
}

export const MEASURE_BINDINGS: Record<string, MeasureBinding> = {
  "adult_immunization": { rateKey: "adult_immunization", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 3650, enrollment: {"code":"adult-immz-enrolled","valueSet":"urn:workwell:vs:adult-immz-enrollment"}, waiver: {"code":"tdap-contraindication","valueSet":"urn:workwell:vs:tdap-contraindication"}, event: {"code":"tdap-vaccine","valueSet":"urn:workwell:vs:tdap-vaccines","type":"immunization"}, refusal: {"code":"tdap-refusal","valueSet":"urn:workwell:vs:tdap-refusal"} },
  "audiogram": { rateKey: "audiogram", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"hearing-enrollment","valueSet":"urn:workwell:vs:hearing-enrollment"}, waiver: {"code":"audiogram-waiver","valueSet":"urn:workwell:vs:audiogram-waiver"}, event: {"code":"audiogram-procedure","valueSet":"urn:workwell:vs:audiogram-procedures","type":"procedure"} },
  "cholesterol_ldl": { rateKey: "cholesterol_ldl", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"cholesterol-enrolled","valueSet":"urn:workwell:vs:cholesterol-program"}, waiver: {"code":"cholesterol-exempt","valueSet":"urn:workwell:vs:cholesterol-exemption"}, event: {"code":"ldl-lab","valueSet":"urn:workwell:vs:ldl-labs","type":"procedure"} },
  "cms122": { rateKey: "cms122", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"cms122-diabetes","valueSet":"urn:workwell:vs:cms122-diabetes"}, waiver: {"code":"cms122-excluded","valueSet":"urn:workwell:vs:cms122-excluded"}, event: {"code":"hba1c-obs","valueSet":"urn:workwell:vs:cms122-hba1c","type":"observation"}, missingDataMeansOutOfPopulation: true },
  "cms125": { rateKey: "cms125", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 820, enrollment: {"code":"cms125-eligible","valueSet":"urn:workwell:vs:cms125-eligible"}, waiver: {"code":"cms125-excluded","valueSet":"urn:workwell:vs:cms125-excluded"}, event: {"code":"mammogram","valueSet":"urn:workwell:vs:cms125-mammogram","type":"procedure"}, missingDataMeansOutOfPopulation: true },
  "diabetes_hba1c": { rateKey: "diabetes_hba1c", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 180, enrollment: {"code":"diabetes-enrolled","valueSet":"urn:workwell:vs:diabetes-program"}, waiver: {"code":"diabetes-exempt","valueSet":"urn:workwell:vs:diabetes-exemption"}, event: {"code":"hba1c-lab","valueSet":"urn:workwell:vs:hba1c-labs","type":"procedure"} },
  "flu_vaccine": { rateKey: "flu_vaccine", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"clinical-role","valueSet":"urn:workwell:vs:clinical-roles"}, waiver: {"code":"flu-exemption","valueSet":"urn:workwell:vs:flu-exemption"}, event: {"code":"flu-vaccine","valueSet":"urn:workwell:vs:flu-vaccines","type":"immunization"} },
  "hazwoper": { rateKey: "hazwoper", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"hazwoper-program","valueSet":"urn:workwell:vs:hazwoper-enrollment"}, waiver: {"code":"hazwoper-exemption","valueSet":"urn:workwell:vs:hazwoper-exemption"}, event: {"code":"hazwoper-exam","valueSet":"urn:workwell:vs:hazwoper-exams","type":"procedure"} },
  "hepatitis_b_vaccination_series": { rateKey: "hepatitis_b_vaccination_series", improvementNotation: "increase", complianceClass: "PERMANENT", complianceWindowDays: 0, enrollment: {"code":"immz-enrolled","valueSet":"urn:workwell:vs:immz-enrollment"}, waiver: {"code":"hepb-contraindication","valueSet":"urn:workwell:vs:hepb-contraindication"}, event: {"code":"hepb-vaccine","valueSet":"urn:workwell:vs:hepb-vaccines","type":"immunization"}, refusal: {"code":"hepb-refusal","valueSet":"urn:workwell:vs:hepb-refusal"}, series: {"requiredDoses":2}, alternatives: [{"label":"Heplisav-B","requiredDoses":2,"codes":["189"],"minIntervalDays":[28]},{"label":"Traditional","requiredDoses":3,"codes":["08","43","44","45"],"minIntervalDays":[28,56]}] },
  "hypertension": { rateKey: "hypertension", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"wellness-enrolled","valueSet":"urn:workwell:vs:wellness-enrollment"}, waiver: {"code":"wellness-exempt","valueSet":"urn:workwell:vs:wellness-exemption"}, event: {"code":"bp-screen","valueSet":"urn:workwell:vs:bp-screening","type":"procedure"} },
  "mmr": { rateKey: "mmr", improvementNotation: "increase", complianceClass: "PERMANENT", complianceWindowDays: 0, enrollment: {"code":"immz-enrolled","valueSet":"urn:workwell:vs:immz-enrollment"}, waiver: {"code":"mmr-contraindication","valueSet":"urn:workwell:vs:mmr-contraindication"}, event: {"code":"mmr-vaccine","valueSet":"urn:workwell:vs:mmr-vaccines","type":"immunization"}, refusal: {"code":"mmr-refusal","valueSet":"urn:workwell:vs:mmr-refusal"}, series: {"requiredDoses":2} },
  "obesity_bmi": { rateKey: "obesity_bmi", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"wellness-enrolled","valueSet":"urn:workwell:vs:wellness-enrollment"}, waiver: {"code":"wellness-exempt","valueSet":"urn:workwell:vs:wellness-exemption"}, event: {"code":"bmi-screen","valueSet":"urn:workwell:vs:bmi-screening","type":"procedure"} },
  "tb_surveillance": { rateKey: "tb_surveillance", improvementNotation: "increase", complianceClass: "RECURRING", complianceWindowDays: 365, enrollment: {"code":"tb-program","valueSet":"urn:workwell:vs:tb-eligible-roles"}, waiver: {"code":"tb-exemption","valueSet":"urn:workwell:vs:tb-exemption"}, event: {"code":"tb-screen","valueSet":"urn:workwell:vs:tb-screening","type":"procedure"} },
  "varicella": { rateKey: "varicella", improvementNotation: "increase", complianceClass: "PERMANENT", complianceWindowDays: 0, enrollment: {"code":"immz-enrolled","valueSet":"urn:workwell:vs:immz-enrollment"}, waiver: {"code":"varicella-contraindication","valueSet":"urn:workwell:vs:varicella-contraindication"}, event: {"code":"varicella-vaccine","valueSet":"urn:workwell:vs:varicella-vaccines","type":"immunization"}, refusal: {"code":"varicella-refusal","valueSet":"urn:workwell:vs:varicella-refusal"}, series: {"requiredDoses":2} },
};
