// AUTO-GENERATED by scripts/gen-measure-bindings.mjs from the YAML measure defs — do not edit.
/**
 * Synthetic measure bindings (#107 run pipeline) — the codes/value sets + compliance
 * window the synthetic FHIR bundle builder stamps per employee. `event.type` drives the
 * resource kind: procedure | immunization | observation. Source of truth: the YAML
 * measure definitions (ADR-006); regenerate on re-seed.
 */
export type EventType = "procedure" | "immunization" | "observation";

export interface CodeBinding {
  code: string;
  valueSet: string;
}

export interface MeasureBinding {
  rateKey: string;
  complianceWindowDays: number;
  enrollment: CodeBinding;
  waiver: CodeBinding;
  event: CodeBinding & { type: EventType };
  refusal?: CodeBinding;
}

export const MEASURE_BINDINGS: Record<string, MeasureBinding> = {
  "adult_immunization": { rateKey: "adult_immunization", complianceWindowDays: 3650, enrollment: {"code":"adult-immz-enrolled","valueSet":"urn:workwell:vs:adult-immz-enrollment"}, waiver: {"code":"tdap-contraindication","valueSet":"urn:workwell:vs:tdap-contraindication"}, event: {"code":"tdap-vaccine","valueSet":"urn:workwell:vs:tdap-vaccines","type":"immunization"}, refusal: {"code":"tdap-refusal","valueSet":"urn:workwell:vs:tdap-refusal"} },
  "audiogram": { rateKey: "audiogram", complianceWindowDays: 365, enrollment: {"code":"hearing-enrollment","valueSet":"urn:workwell:vs:hearing-enrollment"}, waiver: {"code":"audiogram-waiver","valueSet":"urn:workwell:vs:audiogram-waiver"}, event: {"code":"audiogram-procedure","valueSet":"urn:workwell:vs:audiogram-procedures","type":"procedure"} },
  "cholesterol_ldl": { rateKey: "cholesterol_ldl", complianceWindowDays: 365, enrollment: {"code":"cholesterol-enrolled","valueSet":"urn:workwell:vs:cholesterol-program"}, waiver: {"code":"cholesterol-exempt","valueSet":"urn:workwell:vs:cholesterol-exemption"}, event: {"code":"ldl-lab","valueSet":"urn:workwell:vs:ldl-labs","type":"procedure"} },
  "cms122": { rateKey: "cms122", complianceWindowDays: 365, enrollment: {"code":"cms122-diabetes","valueSet":"urn:workwell:vs:cms122-diabetes"}, waiver: {"code":"cms122-excluded","valueSet":"urn:workwell:vs:cms122-excluded"}, event: {"code":"hba1c-obs","valueSet":"urn:workwell:vs:cms122-hba1c","type":"observation"} },
  "cms125": { rateKey: "cms125", complianceWindowDays: 820, enrollment: {"code":"cms125-eligible","valueSet":"urn:workwell:vs:cms125-eligible"}, waiver: {"code":"cms125-excluded","valueSet":"urn:workwell:vs:cms125-excluded"}, event: {"code":"mammogram","valueSet":"urn:workwell:vs:cms125-mammogram","type":"procedure"} },
  "diabetes_hba1c": { rateKey: "diabetes_hba1c", complianceWindowDays: 180, enrollment: {"code":"diabetes-enrolled","valueSet":"urn:workwell:vs:diabetes-program"}, waiver: {"code":"diabetes-exempt","valueSet":"urn:workwell:vs:diabetes-exemption"}, event: {"code":"hba1c-lab","valueSet":"urn:workwell:vs:hba1c-labs","type":"procedure"} },
  "flu_vaccine": { rateKey: "flu_vaccine", complianceWindowDays: 365, enrollment: {"code":"clinical-role","valueSet":"urn:workwell:vs:clinical-roles"}, waiver: {"code":"flu-exemption","valueSet":"urn:workwell:vs:flu-exemption"}, event: {"code":"flu-vaccine","valueSet":"urn:workwell:vs:flu-vaccines","type":"immunization"} },
  "hazwoper": { rateKey: "hazwoper", complianceWindowDays: 365, enrollment: {"code":"hazwoper-program","valueSet":"urn:workwell:vs:hazwoper-enrollment"}, waiver: {"code":"hazwoper-exemption","valueSet":"urn:workwell:vs:hazwoper-exemption"}, event: {"code":"hazwoper-exam","valueSet":"urn:workwell:vs:hazwoper-exams","type":"procedure"} },
  "hypertension": { rateKey: "hypertension", complianceWindowDays: 365, enrollment: {"code":"wellness-enrolled","valueSet":"urn:workwell:vs:wellness-enrollment"}, waiver: {"code":"wellness-exempt","valueSet":"urn:workwell:vs:wellness-exemption"}, event: {"code":"bp-screen","valueSet":"urn:workwell:vs:bp-screening","type":"procedure"} },
  "obesity_bmi": { rateKey: "obesity_bmi", complianceWindowDays: 365, enrollment: {"code":"wellness-enrolled","valueSet":"urn:workwell:vs:wellness-enrollment"}, waiver: {"code":"wellness-exempt","valueSet":"urn:workwell:vs:wellness-exemption"}, event: {"code":"bmi-screen","valueSet":"urn:workwell:vs:bmi-screening","type":"procedure"} },
  "tb_surveillance": { rateKey: "tb_surveillance", complianceWindowDays: 365, enrollment: {"code":"tb-program","valueSet":"urn:workwell:vs:tb-eligible-roles"}, waiver: {"code":"tb-exemption","valueSet":"urn:workwell:vs:tb-exemption"}, event: {"code":"tb-screen","valueSet":"urn:workwell:vs:tb-screening","type":"procedure"} },
};
