// AUTO-GENERATED by scripts/compile-measures.mjs — do not edit.
import lib0 from "./AnnualAudiogramCompleted-1.0.0.elm.json" with { type: "json" };
import lib1 from "./AnnualAudiogramCompletedVS-1.0.0.elm.json" with { type: "json" };
import lib2 from "./CholesterolLDLScreeningCQL-1.0.0.elm.json" with { type: "json" };
import lib3 from "./DiabetesHbA1cPoorControlCQL-1.0.0.elm.json" with { type: "json" };
import lib4 from "./BreastCancerScreeningCQL-1.0.0.elm.json" with { type: "json" };
import lib5 from "./DiabetesHbA1cMonitoringCQL-1.0.0.elm.json" with { type: "json" };
import lib6 from "./FluVaccineSeasonal-1.0.0.elm.json" with { type: "json" };
import lib7 from "./HazwoperSurveillance-1.0.0.elm.json" with { type: "json" };
import lib8 from "./HypertensionBPScreeningCQL-1.0.0.elm.json" with { type: "json" };
import lib9 from "./ObesityBMIScreeningCQL-1.0.0.elm.json" with { type: "json" };
import lib10 from "./TbSurveillance-1.3.0.elm.json" with { type: "json" };
import lib11 from "./FHIRHelpers-4.0.1.elm.json" with { type: "json" };

export const ELM_LIBRARIES: Record<string, unknown> = {
  "AnnualAudiogramCompleted-1.0.0": lib0,
  "AnnualAudiogramCompletedVS-1.0.0": lib1,
  "CholesterolLDLScreeningCQL-1.0.0": lib2,
  "DiabetesHbA1cPoorControlCQL-1.0.0": lib3,
  "BreastCancerScreeningCQL-1.0.0": lib4,
  "DiabetesHbA1cMonitoringCQL-1.0.0": lib5,
  "FluVaccineSeasonal-1.0.0": lib6,
  "HazwoperSurveillance-1.0.0": lib7,
  "HypertensionBPScreeningCQL-1.0.0": lib8,
  "ObesityBMIScreeningCQL-1.0.0": lib9,
  "TbSurveillance-1.3.0": lib10,
  "FHIRHelpers-4.0.1": lib11,
};
